### ISSUE TITLE
Tag packages to specific versions

### ISSUE THREAD

**Issue by arunsathiya** [apeatling/ollama-voice-mac#4]
Followup from https://github.com/apeatling/ollama-voice-mac/issues/3#issuecomment-1884470137

I've noticed that the `requirements.txt` file lists dependencies without specifying their versions. For consistency across different installations, I propose specifying versions for each package.

That would help prevent potential compatibility issues caused by updates to these packages. Additionally, it ensures that all contributors and users of the project are working with a consistent set of dependencies.

**Comment by apeatling** [comment]
Yes good idea, will update!

**Comment by apeatling** [comment]
Fixed. 👍
