### ISSUE TITLE
Segmentation fault when running assistant.py

### ISSUE THREAD

**Issue by Daniel-AT** [apeatling/ollama-voice-mac#5]
Running `assistant.py` on my M3 MacBook returns the following segfault. Is anyone else seeing this? 

`ollama-voice-mac % python3 assistant.py `
`pygame 2.5.2 (SDL 2.28.3, Python 3.12.1)`
`Hello from the pygame community. https://www.pygame.org/contribute.html`
`zsh: segmentation fault  python3 assistant.py`

I appreciate any ideas on how to solve this.

**Comment by apeatling** [comment]
How much RAM do you have?

**Comment by apeatling** [comment]
I was actually able to reproduce this, and fixed it in https://github.com/apeatling/ollama-voice-mac/commit/e101dec18d09e7e60bcb89f4d989b59a07f36e41

Pull the latest and install the requirements again and it should be fixed. 👍

**Comment by Daniel-AT** [comment]
> How much RAM do you have?

I have 16 GB of RAM
