### ISSUE TITLE
After the program starts, the window ends without displaying it

### ISSUE THREAD

**Issue by miandai** [apeatling/ollama-voice-mac#6]
print the events：
![image](https://github.com/apeatling/ollama-voice-mac/assets/4371622/c9809b62-1196-417c-be39-6ee89d8e8c54)
![image](https://github.com/apeatling/ollama-voice-mac/assets/4371622/d3551ae1-0f3e-472c-8ef9-be4ce1da9899)

**Comment by zaengerlein** [comment]
I have the same issue, the windows opens and then it exits without any further info....

**Comment by btessiau** [comment]
Worked for me `pip install py3-tts` (Apple M1 Max)

**Comment by n714** [comment]
after install py3-tts, hold space bar, when released, it's close right away.
