### ISSUE TITLE
After greeting message, Assistant disconnects!

### ISSUE THREAD

**Issue by ileao** [apeatling/ollama-voice-mac#8]
Hi,

After initializing the AI assistant, I hear a greeting message, and it immediately disconnects. There are no error messages in the mac CLI, simply the disconnection of the assistant, without allowing any interaction.

MacBook-Pro-2-of-ileao :ollama-voice-mac ileao$ python3.11 assistant.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html

AI:
Hi, How can I help you?

MacBook-Pro-2-of-ileao :ollama-voice-mac ileao$ python3.11 assistant.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.7)
Hello from the pygame community. https://www.pygame.org/contribute.html

AI:
Hi, How can I help you?

MacBook-Pro-2-of-ileao :ollama-voice-mac ileao$

MacOs Monterey
Version 12.7.2
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2,5 GHz Intel Core i7 Quad-Core
Memory 15 GB 1600 MHz DDR3

Python foundation 3.11.7
Homebrew 4.2.4

Regards,

ileao

**Comment by btessiau** [comment]
Worked for me `pip install py3-tts` (Apple M1 Max)

**Comment by RedemptionC** [comment]
I had the same issue, after `pip install py3-tts`, it doesn't quit immediately, but it doesn't seem to respond to my voice either

**Comment by ileao** [comment]
Thank you for the tip! It has worked out fine! A Py3-TTS file was missing, for some reason.
